In [1]:
import numpy as np

emp = ["Arun", "Bhavana", "Charan", "Divya", "Eshan", "Fathima"]

perf = np.array([
    [78, 82, 85, 88],
    [65, 70, 68, 74],
    [92, 89, 95, 91],
    [55, 62, 60, 67],
    [81, 79, 84, 87],
    [72, 75, 78, 80]
])

quarters = ["Q1", "Q2", "Q3", "Q4"]

print(emp)

['Arun', 'Bhavana', 'Charan', 'Divya', 'Eshan', 'Fathima']


In [9]:
#total performance
total = np.sum(perf,axis=1)
print(total)

[333 277 367 244 331 305]


In [15]:
#average quaterly performace for every employee
average=np.mean(perf,axis=1)
print(f'Average : ',average)

Average :  [83.25 69.25 91.75 61.   82.75 76.25]


In [4]:
#averageperformance for each quarter
print(f'Quater Average : {np.mean(perf,axis=0)}')

Quater Average : [73.83333333 76.16666667 78.33333333 81.16666667]


In [6]:
#employee with highest total performance
cal = np.argmax(np.sum(perf,axis=1))
print(cal ,":", emp[cal])

2 : Charan


In [11]:
#rank all employee
rank=np.argsort(total[::-1])
for i in rank:
  print(emp[i],":",total[i])

Charan : 367
Eshan : 331
Arun : 333
Bhavana : 277
Fathima : 305
Divya : 244


In [14]:
#percentage growth
growth = (perf[:, 1:] - perf[:, :-1]) / perf[:, :-1] * 100
print("Growth:",np.round(growth, 2))


Growth: [[ 5.13  3.66  3.53]
 [ 7.69 -2.86  8.82]
 [-3.26  6.74 -4.21]
 [12.73 -3.23 11.67]
 [-2.47  6.33  3.57]
 [ 4.17  4.    2.56]]


In [17]:
#avg equal or less than 80
print("Average equal or less than 80 :",np.array(emp)[average >= 80])

Average >= 80: ['Arun' 'Charan' 'Eshan']


In [18]:
#employee whose avg is below 80
print(np.sum(average<70))

2


In [19]:
#highest performance
print(np.max(perf))

95


In [24]:
#employee and quater where highest score
row,col= np.unravel_index(np.argmax(perf), perf.shape)

print("Employee:", emp[row])
print("Quarter:", quarters[col])

Employee: Charan
Quarter: Q3
