In [1]:
import numpy as np

stores = ["Store_A", "Store_B", "Store_C", "Store_D", "Store_E"]

sales = np.array([
    [120000, 135000, 142000, 155000],
    [98000, 105000, 110000, 108000],
    [150000, 148000, 160000, 172000],
    [87000, 92000, 99000, 115000],
    [130000, 138000, 141000, 149000]
])

In [2]:
#calculate total sales for every store
total = np.sum(sales, axis=1)
print(total)

[552000 421000 630000 393000 558000]


In [4]:
#average quarterly sales for every store
avg = np.mean(sales, axis=1)
print(avg)

[138000. 105250. 157500.  98250. 139500.]


In [6]:
#total sales for every quater
q_total = np.sum(sales, axis=0)
print(q_total)

[585000 618000 652000 699000]


In [7]:
#stores with highest annula sales
index = np.argmax(total)
print(stores[index],":",total[index])

Store_C : 630000


In [8]:
#rank stores by annual sales
rank = np.argsort(total[::-1])

for i in rank:
    print(stores[i],":",total[i])

Store_B : 421000
Store_D : 393000
Store_E : 558000
Store_A : 552000
Store_C : 630000


In [12]:
#Quarter-over-quarter growth
growth = (sales[:, 1:] - sales[:, :-1]) / sales[:, :-1] * 100
print("Growth:",np.round(growth, 2))
print("\n")

#Above overall average
overall_average = np.mean(total)
print("Above average:",np.array(stores)[total > overall_average])

Growth: [[12.5   5.19  9.15]
 [ 7.14  4.76 -1.82]
 [-1.33  8.11  7.5 ]
 [ 5.75  7.61 16.16]
 [ 6.15  2.17  5.67]]


Above average: ['Store_A' 'Store_C' 'Store_E']
